version: '3.8'

services:
  mcp-web-automation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-web-automation
    ports:
      - "29527:29527"
    volumes:
      # 挂载配置文件目录
      - ./config:/app/config:ro
      # 挂载数据目录（可读写）
      - ./data:/app/data
      # 挂载日志目录
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    restart: unless-stopped
    # 资源限制（适配2GB内存服务器）
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:29527/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 安全设置
    security_opt:
      - no-new-privileges:true
    # 网络模式
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
